export const dates = [
  {
    date: "10th January 2021",
    title: "Strawberry tart",
    caption:"Snowflake looking strawbeey tart, Yummy!",
    image: "https://ichef.bbci.co.uk/food/ic/food_16x9_1600/recipes/strawberry_crme_ptissire_01349_16x9.jpg",
    details: "This impressive strawberry tart looks as if it’s come straight from an upmarket bakery. You will need to allow plenty of time, but as long as you take it step by step it’s not difficult to make.",
  },
  {
    date: "23rd March 2021",
    title: "Strawberry shortcake cupcakes",
    caption: "I looooove sweet and fresh taste,and this is just so perfect for me.",
    image: "https://ichef.bbci.co.uk/food/ic/food_16x9_1600/recipes/strawberry_shortcake_91461_16x9.jpg",
    details: "strawberry shortbread cupcakes have a double surprise inside! Cut them open to reveal a whole strawberry and a crisp biscuit base. Perfect for picnics and parties.",
  },
  {
    date: "11th May 2021",
    title: "Lemon drizzle swirls",
    caption: "Very tradition,but so good.",
    image: "https://ichef.bbci.co.uk/food/ic/food_16x9_1600/recipes/lemon_drizzle_swirls_69883_16x9.jpg",
    details: "These lemon drizzle swirls are pure, edible joy. Soft sweet dough, swirled with lemon zest and drizzled in a thick, creamy, lemony frosting with a tiny kiss of cardamom.",
  },
  {
    date: "15th August 2021",
    title: "Lemon polenta cake",
    caption: "The easiest making lemon flavour cake,great to take home party.",
    image: "https://ichef.bbci.co.uk/food/ic/food_16x9_1600/recipes/almond_and_lemon_polenta_21317_16x9.jpg",
    details: "Almonds give this lemon polenta cake a wonderful richness and crumbly texture. Served with zesty lemon icing, orange mascarpone and caramelised satsumas.",
  },
  {
    date: "20th November 2021",
    title: "Sunken chocolate amaretto cake",
    caption: "No single word to say! Taste it ,and this is everything!",
    image: "https://ichef.bbci.co.uk/food/ic/food_16x9_1600/recipes/sunken_chocolate_42872_16x9.jpg",
    details: "This is one of those dark, squidgy-bellied chocolate cakes that I turn to gratefully when I have friends over to supper; a gratitude that is always reciprocated. The mixture of ground almonds and amaretto gives a marzipan kick, balancing the bitterness of the chocolate. The amaretti cream alongside brings both smoothness and a fine honeycomb crunch to the velvetiness of the cake.",
  },
  {
    date: "10th December 2021",
    title: "Dark and sumptuous chocolate cake.",
    caption: "This is vegan cake, and is absolutely amazing taste as normal cakes!",
    image: "https://ichef.bbci.co.uk/food/ic/food_16x9_1600/recipes/dark_and_sumptuous_53597_16x9.jpg",
    details:"A vegan chocolate cake to die for from Nigella Lawson's Simply Nigella.",
  },
  {
    date: "15th January 2022",
    title: "Beetroot and chocolate cake",
    caption: "Beetloot lover? Try this amazing cake! You cannot tell this is from beetroot",
    ge: "https://ichef.bbci.co.uk/food/ic/food_16x9_1600/recipes/beetroot_and_chocolate_43743_16x9.jpg",
    details: "chocolate traybake includes grated beetroot which makes for a beautifully moist, sweet cake. It’s topped with a chocolate feathered icing – which looks impressive, but is so easy to do.",
  },
  {
    date: "24th Feburuary 2022",
    title: "Chocolate hazelnut cake",
    caption: "Gotta make birthday cake? this is tradition italian celebration cake.",
    image: "https://ichef.bbci.co.uk/food/ic/food_16x9_1600/recipes/chocolate_and_hazelnut_38207_16x9.jpg",
    details: "We made this as a birthday cake for Italy, which celebrated the 150th anniversary of its unification in 2011. Gianduia is a speciality of the Piedmont region and it’s a mixture of ground hazelnuts and chocolate.",
  },
];
